import React, { useState, useEffect } from 'react';
import { GlassCard } from '../components/GlassCard';
import { SkeletonLoader } from '../components/SkeletonLoader';
import { 
  Upload, 
  FileText, 
  Trash2, 
  Search, 
  Sparkles, 
  FileCode, 
  Copy, 
  Download, 
  RefreshCw,
  X,
  FilePlus2,
  BookOpenCheck
} from 'lucide-react';
import axios from 'axios';
import toast from 'react-hot-toast';
import ReactMarkdown from 'react-markdown';
import { motion } from 'framer-motion';

export const MaterialsPage: React.FC = () => {
  const [materials, setMaterials] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedMaterial, setSelectedMaterial] = useState<any>(null);
  const [summaryData, setSummaryData] = useState<any>(null);
  const [isSummarizing, setIsSummarizing] = useState(false);
  
  // Paste / upload form states
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [pasteText, setPasteText] = useState("");
  const [docTitle, setDocTitle] = useState("");
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);

  useEffect(() => {
    fetchMaterials();
  }, []);

  const fetchMaterials = async () => {
    setIsLoading(true);
    try {
      const res = await axios.get('/api/materials');
      setMaterials(res.data);
    } catch (err) {
      toast.error("Failed to load study materials");
    } finally {
      setIsLoading(false);
    }
  };

  const handleFileUpload = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!uploadFile && !pasteText) {
      toast.error("Please provide either a file or pasted text");
      return;
    }

    setIsUploading(true);
    const formData = new FormData();
    if (uploadFile) {
      formData.append('file', uploadFile);
    } else {
      formData.append('text', pasteText);
      formData.append('title', docTitle || "Pasted Document");
    }

    try {
      await axios.post('/api/upload', formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      toast.success("Document uploaded successfully!");
      setPasteText("");
      setDocTitle("");
      setUploadFile(null);
      setShowUploadModal(false);
      fetchMaterials();
    } catch (err: any) {
      const msg = err.response?.data?.message || "Upload failed";
      toast.error(msg);
    } finally {
      setIsUploading(false);
    }
  };

  const handleDeleteMaterial = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!confirm("Are you sure you want to delete this study material?")) return;
    try {
      await axios.delete(`/api/material/${id}`);
      toast.success("Document deleted");
      if (selectedMaterial?.id === id) {
        setSelectedMaterial(null);
        setSummaryData(null);
      }
      fetchMaterials();
    } catch (err) {
      toast.error("Failed to delete document");
    }
  };

  const handleSelectMaterial = (mat: any) => {
    setSelectedMaterial(mat);
    if (mat.summary) {
      setSummaryData(typeof mat.summary === 'string' ? JSON.parse(mat.summary) : mat.summary);
    } else {
      setSummaryData(null);
    }
  };

  const handleGenerateSummary = async () => {
    if (!selectedMaterial) return;
    setIsSummarizing(true);
    try {
      const res = await axios.post('/api/summary', { material_id: selectedMaterial.id });
      setSummaryData(res.data);
      toast.success("Summary generated by AI!");
      fetchMaterials(); // Reload list to update cached status
    } catch (err) {
      toast.error("Failed to generate summary");
    } finally {
      setIsSummarizing(false);
    }
  };

  const handleCopySummary = () => {
    if (!summaryData?.summary) return;
    navigator.clipboard.writeText(summaryData.summary);
    toast.success("Summary copied to clipboard!");
  };

  const handleDownloadPDF = async () => {
    if (!selectedMaterial) return;
    try {
      toast.loading("Generating PDF...", { id: 'pdf_download' });
      const response = await axios.get(`/api/material/${selectedMaterial.id}/download-pdf`, {
        responseType: 'blob'
      });
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${selectedMaterial.title}_summary.pdf`);
      document.body.appendChild(link);
      link.click();
      toast.dismiss('pdf_download');
      toast.success("Summary PDF downloaded!");
    } catch (err) {
      toast.dismiss('pdf_download');
      toast.error("Failed to download PDF summary");
    }
  };

  const filteredMaterials = materials.filter(m => 
    m.title.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-8">
      
      {/* Header title */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight">Study Material Repository</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Maintain your study sheets, generate markdown highlights, and download reference worksheets.
          </p>
        </div>
        <button
          onClick={() => setShowUploadModal(true)}
          className="px-6 py-3 rounded-xl bg-gradient-to-r from-primary to-secondary hover:shadow-lg hover:shadow-primary/20 text-white font-bold text-sm flex items-center space-x-2 transition-all hover:scale-105"
        >
          <FilePlus2 className="h-5 w-5" />
          <span>Upload Document</span>
        </button>
      </div>

      {/* Main interface layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Side: Material selection list */}
        <div className="space-y-6 lg:col-span-1">
          {/* Search bar */}
          <div className="relative">
            <Search className="absolute left-4 top-3.5 h-4.5 w-4.5 text-slate-450" />
            <input
              type="text"
              placeholder="Search materials..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-11 pr-4 py-3 rounded-xl bg-cardLight dark:bg-slate-900/60 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-white placeholder-slate-400 focus:outline-none focus:border-primary transition-all text-sm shadow-sm"
            />
          </div>

          {/* List items */}
          <div className="space-y-3 max-h-[600px] overflow-y-auto pr-1">
            {isLoading ? (
              <SkeletonLoader type="line" count={6} />
            ) : filteredMaterials.length === 0 ? (
              <div className="p-8 text-center text-slate-400 border-2 border-dashed border-slate-200 dark:border-white/5 rounded-2xl">
                <FileText className="h-10 w-10 mx-auto mb-2 text-slate-300" />
                <p className="text-sm">No documents found. Upload one to get started!</p>
              </div>
            ) : (
              filteredMaterials.map((mat) => (
                <div
                  key={mat.id}
                  onClick={() => handleSelectMaterial(mat)}
                  className={`p-4 rounded-xl border transition-all cursor-pointer flex items-center justify-between group
                    ${selectedMaterial?.id === mat.id
                      ? 'bg-primary/10 border-primary/40 text-primary'
                      : 'bg-cardLight dark:bg-cardDark/50 border-slate-200 dark:border-white/5 hover:border-slate-350 dark:hover:border-white/15'
                    }
                  `}
                >
                  <div className="flex items-center space-x-3 overflow-hidden">
                    <FileText className={`h-5 w-5 ${selectedMaterial?.id === mat.id ? 'text-primary' : 'text-slate-400'}`} />
                    <div className="overflow-hidden">
                      <p className="font-bold text-sm truncate text-slate-750 dark:text-slate-250">{mat.title}</p>
                      <span className="text-[10px] text-slate-400 uppercase font-semibold">{mat.content_type}</span>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    {mat.summary && (
                      <span className="h-2 w-2 rounded-full bg-success" title="Summary Available" />
                    )}
                    <button
                      onClick={(e) => handleDeleteMaterial(mat.id, e)}
                      className="p-1.5 rounded-lg hover:bg-rose-500/10 text-rose-400 opacity-0 group-hover:opacity-100 transition-opacity"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Right Side: Summary preview and Markdown viewer */}
        <div className="lg:col-span-2 space-y-6">
          {selectedMaterial ? (
            <GlassCard hoverGlow={false} className="flex flex-col min-h-[400px]">
              
              {/* Document heading */}
              <div className="flex justify-between items-center pb-4 border-b border-slate-200 dark:border-white/5 mb-6">
                <div>
                  <h3 className="font-extrabold text-xl">{selectedMaterial.title}</h3>
                  <span className="text-xs text-slate-400">Content Size: {Math.round(selectedMaterial.raw_text.length / 100) / 10} KB</span>
                </div>
                <div className="flex space-x-2">
                  {summaryData && (
                    <>
                      <button 
                        onClick={handleCopySummary}
                        className="p-2 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-600 dark:text-slate-200"
                        title="Copy Summary Markdown"
                      >
                        <Copy className="h-4 w-4" />
                      </button>
                      <button 
                        onClick={handleDownloadPDF}
                        className="p-2 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-600 dark:text-slate-200"
                        title="Download Summary PDF"
                      >
                        <Download className="h-4 w-4" />
                      </button>
                    </>
                  )}
                  <button 
                    onClick={handleGenerateSummary}
                    disabled={isSummarizing}
                    className="px-4 py-2 rounded-xl bg-gradient-to-r from-primary to-secondary text-white font-bold text-xs flex items-center space-x-2"
                  >
                    {isSummarizing ? (
                      <>
                        <RefreshCw className="h-4 w-4 animate-spin" />
                        <span>Analyzing...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4" />
                        <span>{summaryData ? "Regenerate" : "Generate Summary"}</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Document summary viewer */}
              {summaryData ? (
                <div className="space-y-6">
                  {/* Markdown text summary */}
                  <div className="prose prose-invert max-w-none text-slate-700 dark:text-slate-200 text-sm leading-relaxed border-b border-slate-200 dark:border-white/5 pb-6">
                    <ReactMarkdown>{summaryData.summary}</ReactMarkdown>
                  </div>
                  
                  {/* Key Takeaways */}
                  {summaryData.key_points && (
                    <div className="space-y-2">
                      <h4 className="font-extrabold text-sm text-secondary uppercase tracking-wider">Key Takeaways</h4>
                      <ul className="list-disc pl-5 space-y-1.5 text-sm text-slate-600 dark:text-slate-350">
                        {summaryData.key_points.map((pt: string, idx: number) => (
                          <li key={idx}>{pt}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Definitions */}
                  {summaryData.definitions && summaryData.definitions.length > 0 && (
                    <div className="space-y-3 pt-4 border-t border-slate-200 dark:border-white/5">
                      <h4 className="font-extrabold text-sm text-primary uppercase tracking-wider">Definitions</h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {summaryData.definitions.map((def: any, idx: number) => (
                          <div key={idx} className="p-3.5 rounded-xl bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/5">
                            <span className="font-bold text-sm text-primary">{def.term}</span>
                            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{def.definition}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="flex-1 flex flex-col items-center justify-center p-8 text-center text-slate-455">
                  <BookOpenCheck className="h-14 w-14 text-primary/30 mb-3" />
                  <p className="text-sm max-w-sm">
                    No summary generated yet for this material. Click the button above to generate one using Groq Llama 3.3.
                  </p>
                </div>
              )}

            </GlassCard>
          ) : (
            <div className="p-16 text-center text-slate-450 border-2 border-dashed border-slate-200 dark:border-white/5 rounded-3xl h-full flex flex-col items-center justify-center">
              <FileCode className="h-12 w-12 text-slate-350 dark:text-slate-600 mb-3" />
              <h3 className="font-bold text-lg text-slate-700 dark:text-slate-300">No Document Selected</h3>
              <p className="text-xs max-w-xs mt-1 leading-relaxed">
                Choose a document from the left list, or upload a new syllabus to generate structured summarization guidelines.
              </p>
            </div>
          )}
        </div>

      </div>

      {/* Upload document Modal */}
      {showUploadModal && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex items-center justify-center p-6">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="w-full max-w-lg p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-white/10 shadow-2xl relative"
          >
            <button 
              onClick={() => setShowUploadModal(false)}
              className="absolute top-4 right-4 p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-white/5"
            >
              <X className="h-5 w-5" />
            </button>
            <h3 className="font-extrabold text-xl mb-6">Add Study Material</h3>

            <form onSubmit={handleFileUpload} className="space-y-6">
              
              {/* Tab Selector: Upload File or Paste Text */}
              <div className="space-y-4">
                <div className="flex flex-col space-y-1.5">
                  <label className="text-xs font-bold text-slate-400 uppercase">Document Title</label>
                  <input
                    type="text"
                    placeholder="e.g. Chemistry Chapter 1"
                    value={docTitle}
                    onChange={(e) => setDocTitle(e.target.value)}
                    className="w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-white/10 focus:outline-none focus:border-primary text-sm"
                  />
                </div>

                <div className="flex flex-col space-y-1.5">
                  <label className="text-xs font-bold text-slate-400 uppercase">Document Text Content</label>
                  <textarea
                    placeholder="Paste your text coordinates here..."
                    rows={6}
                    value={pasteText}
                    onChange={(e) => setPasteText(e.target.value)}
                    className="w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-white/10 focus:outline-none focus:border-primary text-sm"
                  />
                </div>

                <div className="relative border-2 border-dashed border-slate-200 dark:border-white/10 rounded-xl p-6 text-center hover:bg-slate-50 dark:hover:bg-slate-950/20 transition-colors">
                  <input
                    type="file"
                    accept=".pdf,.docx,.txt"
                    onChange={(e) => setUploadFile(e.target.files?.[0] || null)}
                    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                  />
                  <Upload className="h-8 w-8 mx-auto mb-2 text-slate-400" />
                  <p className="text-xs text-slate-500 font-medium">
                    {uploadFile ? `Selected: ${uploadFile.name}` : "Or click to upload PDF, DOCX, or TXT file"}
                  </p>
                </div>
              </div>

              <button
                type="submit"
                disabled={isUploading}
                className="w-full py-3.5 rounded-xl bg-gradient-to-r from-primary to-secondary text-white font-bold text-sm flex items-center justify-center space-x-2 transition-all disabled:opacity-50"
              >
                <span>{isUploading ? "Uploading..." : "Save Material"}</span>
              </button>
            </form>
          </motion.div>
        </div>
      )}

    </div>
  );
};
